language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t afeets/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true afeets/react-app npm run test -- --coverage